### ISSUE TITLE
Add read vs REF and read vs ALT dotplots

### ISSUE THREAD

**Issue by amwenger** [nspies/genosv#37]
The genosv dotplots are very useful to understand a variant call, but they only show the variant and not the raw read evidence.  Could you add a few "read vs REF" and "read vs ALT" dotplots?  One idea is to select up to 2 reads that support the REF and 2 reads that support the ALT and include a single page that has dotplots of the 4 reads against both REF and ALT alleles (i.e. 4 rows, one per read; and 2 columns, one per allele).

**Comment by nspies** [comment]
Okay, this now should work, at least in principle. I'm figuring out how to adjust the n-up so that they all end up on one pdf page. Let me know what you think.

Can you send me a few example events where this is interesting in HG2/3/4 so that I can make sure it makes sense to me? The insertion you emailed doesn't include actual inserted sequence.
